sudo: required
language: node_js
node_js:
- '6'
before_install:
- gem install sass
- gem install ruby
- gem install scss_lint
- npm install -g yarn
- yarn add node-sass --dev
before_script:
- yarn install
script:
- yarn prod
- yarn test
