sudo: required
language: node_js
node_js:
- '8'
env:
  global:
    - CC_TEST_REPORTER_ID=324b74767ec6529bb85b80b1d69fee82d3bdeb1e139e441cd83ad39b909907a7
before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
before_script:
- gem install sass
- gem install scss_lint
- npm install -g npm
- npm i
script:
- CI=false npm run prod
- npm run test
- npm run workbox
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  email: false
